# Generated by Django 4.0.3 on 2022-03-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('mobile', models.CharField(max_length=64, unique=True)),
                ('company_name', models.CharField(max_length=64)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logiciel_CRM.users')),
            ],
            bases=('logiciel_CRM.users',),
        ),
        migrations.CreateModel(
            name='SalesStaff',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logiciel_CRM.users')),
            ],
            bases=('logiciel_CRM.users',),
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logiciel_CRM.users')),
            ],
            bases=('logiciel_CRM.users',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('attendees', models.IntegerField()),
                ('notes', models.CharField(max_length=2048)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.customer')),
                ('event_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.eventstatus')),
                ('support_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.supportstaff')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.salesstaff'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.BooleanField()),
                ('payment_due', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.customer')),
                ('sales_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel_CRM.salesstaff')),
            ],
        ),
    ]
