# Generated by Django 4.0.3 on 2022-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel_CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatus',
            name='status_description',
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
