# Generated by Django 4.0.3 on 2022-03-08 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logiciel_CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='logiciel_CRM.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sales_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_customer', to='logiciel_CRM.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_status', to='logiciel_CRM.eventstatus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_support_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
