# Generated by Django 4.0.3 on 2022-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel_CRM', '0002_remove_eventstatus_status_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(null=True),
        ),
    ]
